spring.application.name=tvShow

#server
server.port=8082


spring.data.mongodb.uri=mongodb+srv://bryantdp14:S0p0rt3Ags@cluster0.pdabada.mongodb.net/TDA-QA?retryWrites=true&w=majority
spring.data.mongodb.database=TDA-QA